version: "3"
services:
    mongo:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"

    mcflyapp:
        container_name: mcflyapp
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
